### ISSUE TITLE
how to made data

### ISSUE THREAD

**Issue by junirose** [CNevd/DeepLearning-MXNet#1]
how to made data twitter.pkl??

**Comment by CNevd** [comment]
use cPickle and binarySentiment
https://github.com/CNevd/DeepLearning-MXNet/tree/master/DCNN/data/binarySentiment
data
or you can use read_and_sort_matlab_data directly

2016-10-10 18:56 GMT+08:00 junirose notifications@github.com:

**Comment by junirose** [comment]
I tried to open the link you gave [https://github.com/CNevd/DeepLearning-MXNet/tree/master/DCNN/data/binarySentiment](url)  but the page can not be found.

**Comment by CNevd** [comment]
It was removed to https://raw.githubusercontent.com/CNevd/datasets/master  you can use https://github.com/CNevd/DeepLearning-MXNet/blob/master/DCNN/download.sh to download the file
