### ISSUE TITLE
wide convolution question

### ISSUE THREAD

**Issue by R1ncy** [CNevd/DeepLearning-MXNet#2]
Hi, it's so kind of you to provide the code of DCNN.
I run it and encounter an error. 
It's`File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Invalid Parameter format for pad expect Shape(tuple) but value='(3.5, 0)'`

In this line https://github.com/CNevd/DeepLearning-Mxnet/blob/master/DCNN/dcnn_train.py#L88
the pad=(7/2=3.5, 0), but it should be an int.
And I think the output shape of 1-dim wide convolution should be (s+w-1, xxx) in this paper.
If the input shape of the conv_layer is (batch_size, 1, sentence_size, embed_num), the pad of the convlayer should be (kernel_size-1, 0), instead of (kernel_size/2, 0).
For example,
```
data = mx.sym.Variable('data')
conv = mx.sym.Convolution(data=data, kernel=(7,1), num_filter=6, pad=(7-1,0))
arg_shapes, output_shape, _ = conv.infer_shape(data=(50,1,100,300))
output_shape
Out[6]: [(50, 6, 106, 300)]
```
106 = s+w-1 = 100+7-1

Please do not hesitate to correct me if I am wrong. 
Many thanks!

**Comment by CNevd** [comment]
@R1ncy  thanks to point this, yes u are right, I forgot to correct it
have fixed :)

**Comment by R1ncy** [comment]
great! close it
