### ISSUE TITLE
k max pooling

### ISSUE THREAD

**Issue by R1ncy** [CNevd/DeepLearning-MXNet#3]
have you encountered this?
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\operator.py", line 600, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() keywords must be strings
Traceback (most recent call last):
  File "D:/DeepLearning-MXNet-master/DCNN/dcnn_train.py", line 196, in <module>
    train_dcnn(args,ctx)
  File "D:/DeepLearning-MXNet-master/DCNN/dcnn_train.py", line 126, in train_dcnn
    dcnn = get_dcnn(sentence_size, args.embed_size, args.batch_size, vocab_size)
  File "D:/DeepLearning-MXNet-master/DCNN/dcnn_train.py", line 97, in get_dcnn
    pool_outi = mx.symbol.Custom(data=fold_outi, name='k_max_pool%s' % i, op_type='k_max_pool', k=ki)
  File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
OSError: exception: access violation writing 0x000000D9C3076930
```
seems the k max pooling init failed. 
how to solve it?
thanks a lot

**Comment by CNevd** [comment]
I've run it successfully just now there is no error:)
since it says __init__() keywords must be strings, try to use `k=str(ki)`, I'm not sure if it'll work but you can try:)

**Comment by R1ncy** [comment]
In this line, I set k=str(ki), but seems the same error. :-<
https://github.com/CNevd/DeepLearning-MXNet/blob/master/DCNN/dcnn_train.py#L97
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\operator.py", line 600, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() keywords must be strings
[11:52:13] D:\mxnet-master\dmlc-core\include\dmlc/logging.h:235: [11:52:13] d:\mxnet-master\src\operator\./custom-inl.h:90: Check failed: creator(param_.op_type.c_str(), keys.size(), keys.data(), vals.data(), info_.get()) 
Traceback (most recent call last):
  File "D:/DeepLearning-MXNet-master/DCNN/dcnn_train.py", line 206, in <module>
    train_dcnn(args, ctx)
  File "D:/DeepLearning-MXNet-master/DCNN/dcnn_train.py", line 136, in train_dcnn
    dcnn = get_dcnn(sentence_size, args.embed_size, args.batch_size, vocab_size)
  File "D:/DeepLearning-MXNet-master/DCNN/dcnn_train.py", line 106, in get_dcnn
    pool_outi = mx.symbol.Custom(data=fold_outi, name='k_max_pool%s' % i, op_type='k_max_pool', k=str(ki))
  File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
OSError: exception: access violation writing 0x000000005F4A01F0
```

**Comment by CNevd** [comment]
https://github.com/rg3/youtube-dl/issues/6762
https://github.com/rg3/youtube-dl/issues/3813
may be helpful?

**Comment by R1ncy** [comment]
Thank you!
operator.py has some changed. https://github.com/dmlc/mxnet/issues/3683
modify it like this and there is no error.
https://github.com/dmlc/mxnet/pull/3694/files

**Comment by R1ncy** [comment]
Sorry to bother you again. I have some questions about the output of k-max pooling.

In this paper, the k-max pooling operator is a generalisation of the max pooling over the time dimension used in the Max-TDNN sentence model. Max-TDNN model take the maximum of each row in the resulting matrix c yielding a vector of d values to address the problem of varying sentence lengths.(col: different words, row: different words embed dim)

So I think the k-max pooling takes the k-max values from every col of the input matrix and doesn't change the position of values(row: different words, col: different words embed dim).

I run this code and get the outputs of k-max pooling operator.
```
data = mx.sym.Variable('data')
k_max = mx.symbol.Custom(data=data, op_type='k_max_pool', k=str(1))
input = mx.nd.array(np.array([0.3,0.2,0.1,0.2,0.1,0.3,0.5,0.2,0.2,0.1,0.4,0.4]).reshape((1,1,3,4)),mx.cpu())
print(input.asnumpy())
exe = k_max.bind(mx.cpu(), args = {'data':input})
exe.forward()
print(exe.outputs[0].asnumpy())
```
when k=1, the output is the same as what I think.
but when k=2 and 3, I can't understand the outputs.
when k=2, I think the output is [[0.3, 0.2, 0.5, 0.2], [0.2, 0.3, 0.4, 0.4]]
What's more, in extreme cases k=3, row=k, so the k-max pooling only need to return the input(do nothing).

Please correct me if I'm wrong. Thanks for your attention.

**Comment by CNevd** [comment]
@R1ncy   try `indices_dim3 = np.transpose(np.arange(dim3).repeat(dim2).reshape((dim3,dim2)).repeat(dim0 * dim1, axis = 1)).flatten()`
I'll review the code again soon

**Comment by CNevd** [comment]
@R1ncy code was updated:)

**Comment by R1ncy** [comment]
@CNevd  Thanks for your help!(*๓´╰╯`๓)
I will try it

**Comment by R1ncy** [comment]
I use this code to test forward and backward. From the outputs, there is no error. Thanks again!
```
data = mx.sym.Variable('data')
k_max = mx.symbol.Custom(data=data, op_type='k_max_pool', k=str(1))
input = mx.nd.array(np.array([0.3,0.2,0.1,0.2,0.1,0.3,0.5,0.2,0.2,0.1,0.4,0.4]).reshape((1,1,3,4)),mx.cpu())
arg_shapes, output_shape, _ = k_max.infer_shape(data=(1,1,3,4))
arg_grad = {}
for name, shape in zip(k_max.list_arguments(), arg_shapes):
    arg_grad[name] = mx.nd.empty(shape)
exe = k_max.bind(mx.cpu(), args = {'data':input}, args_grad=arg_grad)
exe.forward()
out = exe.outputs[0]
print(out.asnumpy())

out_grad = mx.nd.ones(shape=output_shape[0])
exe.backward([out_grad])
print(arg_grad['data'].asnumpy())

----output-----
[[[[ 0.30000001  0.30000001  0.5         0.40000001]]]]
[[[[ 1.  0.  0.  0.]
   [ 0.  1.  1.  0.]
   [ 0.  0.  0.  1.]]]]
```
